apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.14-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "3232"
            - name: POSTGRES_USER
              value: docker
            - name: POSTGRES_DB
              value: dockernews